-- 数据库字段注释补齐 V62（基于线上真实结构，修复默认值引号）

ALTER TABLE `app_config` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `app_config` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `app_config` MODIFY COLUMN `status` varchar(16) NOT NULL DEFAULT 'enabled' COMMENT '状态 enabled启用 disabled停用';
ALTER TABLE `app_config` MODIFY COLUMN `remark` varchar(255) NULL COMMENT '备注';
ALTER TABLE `app_config` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `app_config` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `app_config` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `app_user` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `app_user` MODIFY COLUMN `open_id` varchar(64) NOT NULL COMMENT '微信openid';
ALTER TABLE `app_user` MODIFY COLUMN `union_id` varchar(64) NULL COMMENT '微信unionid';
ALTER TABLE `app_user` MODIFY COLUMN `nick_name` varchar(64) NULL COMMENT '昵称';
ALTER TABLE `app_user` MODIFY COLUMN `phone` varchar(20) NULL COMMENT '手机号';
ALTER TABLE `app_user` MODIFY COLUMN `birthday` date NULL COMMENT '生日';
ALTER TABLE `app_user` MODIFY COLUMN `gender` varchar(16) NULL COMMENT '性别';
ALTER TABLE `app_user` MODIFY COLUMN `vip_level` varchar(16) NULL COMMENT '会员等级编码';
ALTER TABLE `app_user` MODIFY COLUMN `business_role` varchar(32) NULL COMMENT '业务角色';
ALTER TABLE `app_user` MODIFY COLUMN `bound_subject_id` bigint unsigned NULL COMMENT '绑定的主体ID';
ALTER TABLE `app_user` MODIFY COLUMN `referrer_id` bigint unsigned NULL COMMENT '推荐人用户ID';
ALTER TABLE `app_user` MODIFY COLUMN `channel_subject_id` bigint unsigned NULL COMMENT '渠道主体ID';
ALTER TABLE `app_user` MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用';
ALTER TABLE `app_user` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `app_user` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `app_user` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `audit_log` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `audit_log` MODIFY COLUMN `operator` varchar(64) NULL COMMENT '操作人';
ALTER TABLE `audit_log` MODIFY COLUMN `module` varchar(64) NULL COMMENT '操作模块';
ALTER TABLE `audit_log` MODIFY COLUMN `action` varchar(64) NULL COMMENT '操作动作';
ALTER TABLE `audit_log` MODIFY COLUMN `target` varchar(255) NULL COMMENT '操作对象';
ALTER TABLE `audit_log` MODIFY COLUMN `before_value` text NULL COMMENT '变更前值';
ALTER TABLE `audit_log` MODIFY COLUMN `after_value` text NULL COMMENT '变更后值';
ALTER TABLE `audit_log` MODIFY COLUMN `reason` varchar(255) NULL COMMENT '原因';
ALTER TABLE `audit_log` MODIFY COLUMN `ip` varchar(64) NULL COMMENT '操作IP';
ALTER TABLE `audit_log` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `audit_log` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `audit_log` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `balance_pay_intent` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `balance_pay_intent` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `balance_pay_intent` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `balance_pay_intent` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `biz_role` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `biz_role` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '角色编码';
ALTER TABLE `biz_role` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '角色名称';
ALTER TABLE `biz_role` MODIFY COLUMN `description` varchar(255) NULL COMMENT '角色描述';
ALTER TABLE `biz_role` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `biz_role` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `biz_role` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `biz_subject` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `biz_subject` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '主体编码';
ALTER TABLE `biz_subject` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '主体名称';
ALTER TABLE `biz_subject` MODIFY COLUMN `status` varchar(32) NULL DEFAULT 'active' COMMENT '状态 active启用/disabled停用';
ALTER TABLE `biz_subject` MODIFY COLUMN `bound_user_id` bigint unsigned NULL COMMENT '绑定的用户ID';
ALTER TABLE `biz_subject` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `biz_subject` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `biz_subject` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `channel_profile` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `channel_profile` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `channel_profile` MODIFY COLUMN `location` varchar(64) NULL COMMENT '位置/区域';
ALTER TABLE `channel_profile` MODIFY COLUMN `store_type` varchar(64) NULL COMMENT '门店类型';
ALTER TABLE `channel_profile` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `channel_profile` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `channel_profile` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `channel_store` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `channel_store` MODIFY COLUMN `channel_subject_id` bigint unsigned NOT NULL COMMENT '渠道主体ID';
ALTER TABLE `channel_store` MODIFY COLUMN `store_subject_id` bigint unsigned NOT NULL COMMENT '门店主体ID';
ALTER TABLE `channel_store` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `channel_store` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `channel_store` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `comments` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `comments` MODIFY COLUMN `order_id` bigint unsigned NOT NULL COMMENT '订单ID';
ALTER TABLE `comments` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `comments` MODIFY COLUMN `rating` int NOT NULL DEFAULT 5 COMMENT '评分';
ALTER TABLE `comments` MODIFY COLUMN `content` text NULL COMMENT '评论内容';
ALTER TABLE `comments` MODIFY COLUMN `images` json NULL COMMENT '评论图片(JSON)';
ALTER TABLE `comments` MODIFY COLUMN `review_time` datetime NULL COMMENT '审核时间';
ALTER TABLE `comments` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `comments` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `comments` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `coupon` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `coupon` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '优惠券编码';
ALTER TABLE `coupon` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '优惠券名称';
ALTER TABLE `coupon` MODIFY COLUMN `type` varchar(32) NULL COMMENT '优惠券类型';
ALTER TABLE `coupon` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '面额（分）';
ALTER TABLE `coupon` MODIFY COLUMN `threshold` bigint NOT NULL DEFAULT 0 COMMENT '使用门槛（分）';
ALTER TABLE `coupon` MODIFY COLUMN `brand` varchar(64) NULL COMMENT '品牌';
ALTER TABLE `coupon` MODIFY COLUMN `scenes` varchar(64) NULL COMMENT '适用场景';
ALTER TABLE `coupon` MODIFY COLUMN `source` varchar(64) NULL COMMENT '来源';
ALTER TABLE `coupon` MODIFY COLUMN `description` text NULL COMMENT '描述';
ALTER TABLE `coupon` MODIFY COLUMN `image` varchar(255) NULL COMMENT '图片URL';
ALTER TABLE `coupon` MODIFY COLUMN `validity_type` varchar(16) NULL COMMENT '有效期类型';
ALTER TABLE `coupon` MODIFY COLUMN `validity_start` datetime NULL COMMENT '有效期开始';
ALTER TABLE `coupon` MODIFY COLUMN `validity_end` datetime NULL COMMENT '有效期结束';
ALTER TABLE `coupon` MODIFY COLUMN `validity_days` int NULL COMMENT '有效期天数';
ALTER TABLE `coupon` MODIFY COLUMN `usage_time` varchar(64) NULL COMMENT '可用时段';
ALTER TABLE `coupon` MODIFY COLUMN `applicable_store_ids` json NULL COMMENT '适用门店ID(JSON)';
ALTER TABLE `coupon` MODIFY COLUMN `applicable_product_ids` json NULL COMMENT '适用商品ID(JSON)';
ALTER TABLE `coupon` MODIFY COLUMN `stock` int NOT NULL DEFAULT 0 COMMENT '库存';
ALTER TABLE `coupon` MODIFY COLUMN `status` varchar(16) NOT NULL DEFAULT 'enabled' COMMENT '状态 enabled启用 disabled停用';
ALTER TABLE `coupon` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `coupon` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `coupon` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `event_outbox` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `event_outbox` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `event_outbox` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `exchange_order` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `exchange_order` MODIFY COLUMN `exchange_no` varchar(64) NOT NULL COMMENT '兑换单号';
ALTER TABLE `exchange_order` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `exchange_order` MODIFY COLUMN `points_product_id` bigint unsigned NOT NULL COMMENT '积分商品ID';
ALTER TABLE `exchange_order` MODIFY COLUMN `points` bigint NOT NULL DEFAULT 0 COMMENT '消耗积分';
ALTER TABLE `exchange_order` MODIFY COLUMN `pickup_code` varchar(64) NULL COMMENT '核销码';
ALTER TABLE `exchange_order` MODIFY COLUMN `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING待处理/COMPLETED已完成等';
ALTER TABLE `exchange_order` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `exchange_order` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `exchange_order` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `feature_flag` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `feature_flag` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '开关编码';
ALTER TABLE `feature_flag` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '开关名称';
ALTER TABLE `feature_flag` MODIFY COLUMN `default_status` varchar(16) NULL COMMENT '默认状态';
ALTER TABLE `feature_flag` MODIFY COLUMN `current_status` varchar(16) NULL COMMENT '当前状态';
ALTER TABLE `feature_flag` MODIFY COLUMN `open_condition` varchar(255) NULL COMMENT '开启条件';
ALTER TABLE `feature_flag` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `feature_flag` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `feature_flag` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `fund_flow` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `fund_flow` MODIFY COLUMN `flow_no` varchar(64) NOT NULL COMMENT '流水号';
ALTER TABLE `fund_flow` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `fund_flow` MODIFY COLUMN `role_type` varchar(32) NOT NULL COMMENT '角色类型';
ALTER TABLE `fund_flow` MODIFY COLUMN `direction` varchar(8) NOT NULL COMMENT '方向 IN入 OUT出';
ALTER TABLE `fund_flow` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '金额（分）';
ALTER TABLE `fund_flow` MODIFY COLUMN `order_no` varchar(64) NULL COMMENT '订单号';
ALTER TABLE `fund_flow` MODIFY COLUMN `balance_after` bigint NOT NULL DEFAULT 0 COMMENT '变动后余额（分）';
ALTER TABLE `fund_flow` MODIFY COLUMN `remark` varchar(255) NULL COMMENT '备注';
ALTER TABLE `fund_flow` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `fund_flow` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `fund_flow` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `fund_pool` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `fund_pool` MODIFY COLUMN `pool_name` varchar(64) NOT NULL COMMENT '资金池名称';
ALTER TABLE `fund_pool` MODIFY COLUMN `total_balance` bigint NOT NULL DEFAULT 0 COMMENT '总余额（分）';
ALTER TABLE `fund_pool` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `fund_pool` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `fund_pool` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `gift_card` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `gift_card` MODIFY COLUMN `card_no` varchar(64) NOT NULL COMMENT '卡号';
ALTER TABLE `gift_card` MODIFY COLUMN `denomination_id` bigint unsigned NOT NULL COMMENT '面额ID';
ALTER TABLE `gift_card` MODIFY COLUMN `status` varchar(32) NOT NULL DEFAULT 'INACTIVE' COMMENT '状态 INACTIVE未激活/ACTIVE已激活等';
ALTER TABLE `gift_card` MODIFY COLUMN `owner_user_id` bigint unsigned NULL COMMENT '持卡用户ID';
ALTER TABLE `gift_card` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `gift_card` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `gift_card` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '面额编码';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '面额名称';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '面额金额（分）';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `status` varchar(16) NOT NULL DEFAULT 'enabled' COMMENT '状态 enabled启用 disabled停用';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `gift_card_denomination` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `gift_card_group` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '分组编码';
ALTER TABLE `gift_card_group` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '分组名称';
ALTER TABLE `gift_card_group` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `gift_card_group` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `gift_card_group` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `gift_card_group` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `gift_card_order` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `gift_card_order` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '购买单号';
ALTER TABLE `gift_card_order` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `gift_card_order` MODIFY COLUMN `denomination_id` bigint unsigned NOT NULL COMMENT '面额ID';
ALTER TABLE `gift_card_order` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '金额（分）';
ALTER TABLE `gift_card_order` MODIFY COLUMN `pay_status` varchar(16) NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态 UNPAID未支付/PAID已支付';
ALTER TABLE `gift_card_order` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `gift_card_order` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `gift_card_order` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `gift_card_refund` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `gift_card_refund` MODIFY COLUMN `refund_no` varchar(64) NOT NULL COMMENT '退款单号';
ALTER TABLE `gift_card_refund` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '购买单号';
ALTER TABLE `gift_card_refund` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `gift_card_refund` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `gift_card_refund` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `growth_record` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `growth_record` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `growth_record` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '订单号';
ALTER TABLE `growth_record` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `growth_record` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `growth_record` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `investor_profile` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `investor_profile` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `investor_profile` MODIFY COLUMN `investable_store_count` int NOT NULL DEFAULT 0 COMMENT '可投门店数';
ALTER TABLE `investor_profile` MODIFY COLUMN `sign_status` varchar(32) NULL COMMENT '签约状态';
ALTER TABLE `investor_profile` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `investor_profile` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `investor_profile` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `member_level` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `member_level` MODIFY COLUMN `level_code` varchar(16) NOT NULL COMMENT '等级编码';
ALTER TABLE `member_level` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '等级名称';
ALTER TABLE `member_level` MODIFY COLUMN `discount` varchar(16) NULL COMMENT '折扣';
ALTER TABLE `member_level` MODIFY COLUMN `benefits` json NULL COMMENT '权益(JSON)';
ALTER TABLE `member_level` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `member_level` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `member_level` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `member_level` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `order_item` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `order_item` MODIFY COLUMN `order_id` bigint unsigned NOT NULL COMMENT '订单ID';
ALTER TABLE `order_item` MODIFY COLUMN `product_id` varchar(64) NOT NULL COMMENT '商品ID';
ALTER TABLE `order_item` MODIFY COLUMN `product_name` varchar(128) NOT NULL COMMENT '商品名称';
ALTER TABLE `order_item` MODIFY COLUMN `unit_price` bigint NOT NULL DEFAULT 0 COMMENT '单价（分）';
ALTER TABLE `order_item` MODIFY COLUMN `original_price` bigint NOT NULL DEFAULT 0 COMMENT '原价（分）';
ALTER TABLE `order_item` MODIFY COLUMN `quantity` int NOT NULL DEFAULT 1 COMMENT '数量';
ALTER TABLE `order_item` MODIFY COLUMN `sub_total` bigint NOT NULL DEFAULT 0 COMMENT '小计（分）';
ALTER TABLE `order_item` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `order_item` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `order_item` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `orders` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `orders` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '订单号';
ALTER TABLE `orders` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `orders` MODIFY COLUMN `store_subject_id` bigint unsigned NOT NULL COMMENT '门店主体ID';
ALTER TABLE `orders` MODIFY COLUMN `channel_subject_id` bigint unsigned NULL COMMENT '渠道主体ID';
ALTER TABLE `orders` MODIFY COLUMN `meal_type` varchar(16) NULL COMMENT '餐段类型';
ALTER TABLE `orders` MODIFY COLUMN `pickup_time` datetime NULL COMMENT '取餐时间';
ALTER TABLE `orders` MODIFY COLUMN `status` varchar(32) NOT NULL DEFAULT 'CREATED' COMMENT '订单状态';
ALTER TABLE `orders` MODIFY COLUMN `pay_status` varchar(16) NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态 UNPAID/PAID/REFUNDED等';
ALTER TABLE `orders` MODIFY COLUMN `pickup_code` varchar(32) NULL COMMENT '取餐码';
ALTER TABLE `orders` MODIFY COLUMN `total_amount` bigint NOT NULL DEFAULT 0 COMMENT '实付总额（分）';
ALTER TABLE `orders` MODIFY COLUMN `original_amount` bigint NOT NULL DEFAULT 0 COMMENT '原始总额（分）';
ALTER TABLE `orders` MODIFY COLUMN `discount_amount` bigint NOT NULL DEFAULT 0 COMMENT '优惠金额（分）';
ALTER TABLE `orders` MODIFY COLUMN `paid_amount` bigint NOT NULL DEFAULT 0 COMMENT '已支付金额（分）';
ALTER TABLE `orders` MODIFY COLUMN `coupon_id` bigint unsigned NULL COMMENT '优惠券ID';
ALTER TABLE `orders` MODIFY COLUMN `coupon_discount` bigint NOT NULL DEFAULT 0 COMMENT '优惠券抵扣（分）';
ALTER TABLE `orders` MODIFY COLUMN `points_used` bigint NOT NULL DEFAULT 0 COMMENT '使用积分';
ALTER TABLE `orders` MODIFY COLUMN `points_earned` bigint NOT NULL DEFAULT 0 COMMENT '获得积分';
ALTER TABLE `orders` MODIFY COLUMN `refund_status` varchar(32) NULL COMMENT '退款状态';
ALTER TABLE `orders` MODIFY COLUMN `remark` varchar(255) NULL COMMENT '备注';
ALTER TABLE `orders` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `orders` MODIFY COLUMN `pay_time` datetime NULL COMMENT '支付时间';
ALTER TABLE `orders` MODIFY COLUMN `verify_time` datetime NULL COMMENT '核销时间';
ALTER TABLE `orders` MODIFY COLUMN `complete_time` datetime NULL COMMENT '完成时间';
ALTER TABLE `orders` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `orders` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `payment` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `payment` MODIFY COLUMN `payment_no` varchar(64) NOT NULL COMMENT '支付单号';
ALTER TABLE `payment` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '金额（分）';
ALTER TABLE `payment` MODIFY COLUMN `channel` varchar(16) NOT NULL COMMENT '支付渠道';
ALTER TABLE `payment` MODIFY COLUMN `third_status` varchar(32) NULL COMMENT '第三方状态';
ALTER TABLE `payment` MODIFY COLUMN `standard_status` varchar(32) NULL COMMENT '标准状态';
ALTER TABLE `payment` MODIFY COLUMN `transaction_id` varchar(64) NULL COMMENT '第三方交易号';
ALTER TABLE `payment` MODIFY COLUMN `callback_time` datetime NULL COMMENT '回调时间';
ALTER TABLE `payment` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `payment` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `payment` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `platform_profile` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `platform_profile` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `platform_profile` MODIFY COLUMN `app_id` varchar(64) NULL COMMENT '小程序appid';
ALTER TABLE `platform_profile` MODIFY COLUMN `app_secret` varchar(128) NULL COMMENT '小程序secret';
ALTER TABLE `platform_profile` MODIFY COLUMN `pay_config` json NULL COMMENT '支付配置(JSON)';
ALTER TABLE `platform_profile` MODIFY COLUMN `split_default` json NULL COMMENT '默认分账配置(JSON)';
ALTER TABLE `platform_profile` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `platform_profile` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `platform_profile` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `points_category` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `points_category` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `points_category` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `points_category` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '规则编码';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `action` varchar(128) NOT NULL COMMENT '触发动作';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `reward` varchar(64) NULL COMMENT '奖励';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `note` varchar(255) NULL COMMENT '说明';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `points_earning_rule` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `points_product` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `points_product` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '商品编码';
ALTER TABLE `points_product` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '商品名称';
ALTER TABLE `points_product` MODIFY COLUMN `image` varchar(255) NULL COMMENT '图片URL';
ALTER TABLE `points_product` MODIFY COLUMN `points` bigint NOT NULL DEFAULT 0 COMMENT '所需积分';
ALTER TABLE `points_product` MODIFY COLUMN `stock` int NOT NULL DEFAULT 0 COMMENT '库存';
ALTER TABLE `points_product` MODIFY COLUMN `badge` varchar(64) NULL COMMENT '角标';
ALTER TABLE `points_product` MODIFY COLUMN `limit_text` varchar(255) NULL COMMENT '限制说明';
ALTER TABLE `points_product` MODIFY COLUMN `description` text NULL COMMENT '描述';
ALTER TABLE `points_product` MODIFY COLUMN `status` varchar(16) NOT NULL DEFAULT 'enabled' COMMENT '状态 enabled启用 disabled停用';
ALTER TABLE `points_product` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `points_product` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `points_product` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `points_record` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `points_record` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `points_record` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '变动积分';
ALTER TABLE `points_record` MODIFY COLUMN `balance_after` bigint NOT NULL DEFAULT 0 COMMENT '变动后积分';
ALTER TABLE `points_record` MODIFY COLUMN `source` varchar(32) NULL COMMENT '来源';
ALTER TABLE `points_record` MODIFY COLUMN `order_no` varchar(64) NULL COMMENT '订单号';
ALTER TABLE `points_record` MODIFY COLUMN `remark` varchar(255) NULL COMMENT '备注';
ALTER TABLE `points_record` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `points_record` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `points_record` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `points_signin` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `points_signin` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `points_signin` MODIFY COLUMN `sign_date` date NOT NULL COMMENT '签到日期';
ALTER TABLE `points_signin` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `points_signin` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `points_signin` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `points_signin_rule` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `points_signin_rule` MODIFY COLUMN `daily` bigint NOT NULL DEFAULT 0 COMMENT '每日积分';
ALTER TABLE `points_signin_rule` MODIFY COLUMN `streak_days` int NOT NULL DEFAULT 0 COMMENT '连续天数';
ALTER TABLE `points_signin_rule` MODIFY COLUMN `streak_reward` bigint NOT NULL DEFAULT 0 COMMENT '连续奖励积分';
ALTER TABLE `points_signin_rule` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `points_signin_rule` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `points_signin_rule` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `product` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `product` MODIFY COLUMN `product_id` varchar(64) NOT NULL COMMENT '商品业务ID';
ALTER TABLE `product` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '商品编码';
ALTER TABLE `product` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '商品名称';
ALTER TABLE `product` MODIFY COLUMN `tags` json NULL COMMENT '标签(JSON)';
ALTER TABLE `product` MODIFY COLUMN `description` text NULL COMMENT '描述';
ALTER TABLE `product` MODIFY COLUMN `price` bigint NOT NULL DEFAULT 0 COMMENT '售价（分）';
ALTER TABLE `product` MODIFY COLUMN `original_price` bigint NOT NULL DEFAULT 0 COMMENT '原价（分）';
ALTER TABLE `product` MODIFY COLUMN `stored_value_price` bigint NOT NULL DEFAULT 0 COMMENT '储值价（分）';
ALTER TABLE `product` MODIFY COLUMN `image` varchar(255) NULL COMMENT '图片URL';
ALTER TABLE `product` MODIFY COLUMN `ingredients` varchar(255) NULL COMMENT '配料';
ALTER TABLE `product` MODIFY COLUMN `allergens` varchar(255) NULL COMMENT '过敏原';
ALTER TABLE `product` MODIFY COLUMN `cup_capacity` varchar(255) NULL COMMENT '杯型/容量';
ALTER TABLE `product` MODIFY COLUMN `tips` json NULL COMMENT '提示(JSON)';
ALTER TABLE `product` MODIFY COLUMN `on_sale` tinyint NOT NULL DEFAULT 1 COMMENT '1上架 0下架';
ALTER TABLE `product` MODIFY COLUMN `split_rule_id` bigint unsigned NULL COMMENT '分账规则ID';
ALTER TABLE `product` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `product` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `product` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `product_category` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `product_category` MODIFY COLUMN `parent_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '父分类ID';
ALTER TABLE `product_category` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '分类编码';
ALTER TABLE `product_category` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '分类名称';
ALTER TABLE `product_category` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `product_category` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `product_category` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `product_category` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `product_spec` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `product_spec` MODIFY COLUMN `product_id` bigint unsigned NOT NULL COMMENT '商品ID';
ALTER TABLE `product_spec` MODIFY COLUMN `group_code` varchar(64) NOT NULL COMMENT '规格组编码';
ALTER TABLE `product_spec` MODIFY COLUMN `group_label` varchar(64) NOT NULL COMMENT '规格组名称';
ALTER TABLE `product_spec` MODIFY COLUMN `option_code` varchar(64) NOT NULL COMMENT '规格项编码';
ALTER TABLE `product_spec` MODIFY COLUMN `option_label` varchar(64) NOT NULL COMMENT '规格项名称';
ALTER TABLE `product_spec` MODIFY COLUMN `price_delta` bigint NOT NULL DEFAULT 0 COMMENT '加价（分）';
ALTER TABLE `product_spec` MODIFY COLUMN `selected` tinyint NOT NULL DEFAULT 0 COMMENT '1默认选中 0未选';
ALTER TABLE `product_spec` MODIFY COLUMN `icon` varchar(255) NULL COMMENT '图标';
ALTER TABLE `product_spec` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `product_spec` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `product_spec` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `product_spec` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `product_store` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `product_store` MODIFY COLUMN `product_id` bigint unsigned NOT NULL COMMENT '商品ID';
ALTER TABLE `product_store` MODIFY COLUMN `store_subject_id` bigint unsigned NOT NULL COMMENT '门店主体ID';
ALTER TABLE `product_store` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `product_store` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `product_store` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `issue_type` varchar(32) NOT NULL COMMENT '异常类型';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '订单号';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `system_value` varchar(64) NULL COMMENT '系统值';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `third_value` varchar(64) NULL COMMENT '第三方值';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `diff_amount` bigint NOT NULL DEFAULT 0 COMMENT '差额（分）';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `found_time` datetime NULL COMMENT '发现时间';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `status` varchar(32) NULL COMMENT '状态';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `reconcile_issue` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `referral_config` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `referral_config` MODIFY COLUMN `config` json NULL COMMENT '邀请配置(JSON)';
ALTER TABLE `referral_config` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `referral_config` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `referral_config` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `referral_record` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `referral_record` MODIFY COLUMN `inviter_user_id` bigint unsigned NOT NULL COMMENT '邀请人用户ID';
ALTER TABLE `referral_record` MODIFY COLUMN `invitee_user_id` bigint unsigned NOT NULL COMMENT '被邀请人用户ID';
ALTER TABLE `referral_record` MODIFY COLUMN `status` varchar(32) NULL COMMENT '状态';
ALTER TABLE `referral_record` MODIFY COLUMN `first_order_status` varchar(16) NULL COMMENT '首单状态';
ALTER TABLE `referral_record` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `referral_record` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `referral_record` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `refund` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `refund` MODIFY COLUMN `refund_no` varchar(64) NOT NULL COMMENT '退款单号';
ALTER TABLE `refund` MODIFY COLUMN `order_id` bigint unsigned NOT NULL COMMENT '订单ID';
ALTER TABLE `refund` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '订单号';
ALTER TABLE `refund` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '退款金额（分）';
ALTER TABLE `refund` MODIFY COLUMN `status` varchar(32) NULL COMMENT '退款状态';
ALTER TABLE `refund` MODIFY COLUMN `reason` varchar(255) NULL COMMENT '退款原因';
ALTER TABLE `refund` MODIFY COLUMN `apply_time` datetime NULL COMMENT '申请时间';
ALTER TABLE `refund` MODIFY COLUMN `review_time` datetime NULL COMMENT '审核时间';
ALTER TABLE `refund` MODIFY COLUMN `complete_time` datetime NULL COMMENT '完成时间';
ALTER TABLE `refund` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `refund` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `refund` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `region` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `region` MODIFY COLUMN `parent_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '父级ID';
ALTER TABLE `region` MODIFY COLUMN `code` varchar(32) NOT NULL COMMENT '区域编码';
ALTER TABLE `region` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '区域名称';
ALTER TABLE `region` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `region` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `region` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `region` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `role_application` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `role_application` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `role_application` MODIFY COLUMN `role_type` varchar(32) NOT NULL COMMENT '申请角色类型';
ALTER TABLE `role_application` MODIFY COLUMN `status` varchar(32) NOT NULL DEFAULT 'PENDING' COMMENT '状态 PENDING待审核/APPROVED已通过/REJECTED已驳回';
ALTER TABLE `role_application` MODIFY COLUMN `apply_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '申请时间';
ALTER TABLE `role_application` MODIFY COLUMN `review_time` datetime NULL COMMENT '审核时间';
ALTER TABLE `role_application` MODIFY COLUMN `reviewer` varchar(64) NULL COMMENT '审核人';
ALTER TABLE `role_application` MODIFY COLUMN `subject_id` bigint unsigned NULL COMMENT '主体ID';
ALTER TABLE `role_application` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `role_application` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `role_application` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `settlement_record` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `settlement_record` MODIFY COLUMN `record_no` varchar(64) NOT NULL COMMENT '结算单号';
ALTER TABLE `settlement_record` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `settlement_record` MODIFY COLUMN `snapshot_id` bigint unsigned NULL COMMENT '分账快照ID';
ALTER TABLE `settlement_record` MODIFY COLUMN `order_id` bigint unsigned NULL COMMENT '订单ID';
ALTER TABLE `settlement_record` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '金额（分）';
ALTER TABLE `settlement_record` MODIFY COLUMN `settle_date` date NULL COMMENT '结算日期';
ALTER TABLE `settlement_record` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `settlement_record` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `settlement_record` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `spec_group_template` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `spec_group_template` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '规格组编码';
ALTER TABLE `spec_group_template` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '规格组名称';
ALTER TABLE `spec_group_template` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `spec_group_template` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `spec_group_template` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `spec_group_template` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `spec_option_template` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `spec_option_template` MODIFY COLUMN `group_id` bigint unsigned NOT NULL COMMENT '规格组ID';
ALTER TABLE `spec_option_template` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '选项编码';
ALTER TABLE `spec_option_template` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '选项名称';
ALTER TABLE `spec_option_template` MODIFY COLUMN `price_delta` bigint NOT NULL DEFAULT 0 COMMENT '加价（分）';
ALTER TABLE `spec_option_template` MODIFY COLUMN `icon` varchar(255) NULL COMMENT '图标';
ALTER TABLE `spec_option_template` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `spec_option_template` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `spec_option_template` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `spec_option_template` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `split_rule` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `split_rule` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '规则编码';
ALTER TABLE `split_rule` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '规则名称';
ALTER TABLE `split_rule` MODIFY COLUMN `product_id` bigint unsigned NULL COMMENT '商品ID';
ALTER TABLE `split_rule` MODIFY COLUMN `platform_ratio` int NOT NULL DEFAULT 0 COMMENT '平台分账比例(万分比)';
ALTER TABLE `split_rule` MODIFY COLUMN `store_ratio` int NOT NULL DEFAULT 0 COMMENT '门店分账比例(万分比)';
ALTER TABLE `split_rule` MODIFY COLUMN `channel_ratio` int NOT NULL DEFAULT 0 COMMENT '渠道分账比例(万分比)';
ALTER TABLE `split_rule` MODIFY COLUMN `investor_ratio` int NOT NULL DEFAULT 0 COMMENT '投资人分账比例(万分比)';
ALTER TABLE `split_rule` MODIFY COLUMN `supplier_ratio` int NOT NULL DEFAULT 0 COMMENT '供应商分账比例(万分比)';
ALTER TABLE `split_rule` MODIFY COLUMN `status` varchar(16) NOT NULL DEFAULT 'enabled' COMMENT '状态 enabled启用 disabled停用';
ALTER TABLE `split_rule` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `split_rule` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `split_rule` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `split_snapshot` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `split_snapshot` MODIFY COLUMN `snapshot_no` varchar(64) NOT NULL COMMENT '快照编号';
ALTER TABLE `split_snapshot` MODIFY COLUMN `order_id` bigint unsigned NOT NULL COMMENT '订单ID';
ALTER TABLE `split_snapshot` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '订单号';
ALTER TABLE `split_snapshot` MODIFY COLUMN `item_count` int NOT NULL DEFAULT 0 COMMENT '明细数';
ALTER TABLE `split_snapshot` MODIFY COLUMN `platform_amount` bigint NOT NULL DEFAULT 0 COMMENT '平台金额（分）';
ALTER TABLE `split_snapshot` MODIFY COLUMN `store_amount` bigint NOT NULL DEFAULT 0 COMMENT '门店金额（分）';
ALTER TABLE `split_snapshot` MODIFY COLUMN `channel_amount` bigint NOT NULL DEFAULT 0 COMMENT '渠道金额（分）';
ALTER TABLE `split_snapshot` MODIFY COLUMN `investor_amount` bigint NOT NULL DEFAULT 0 COMMENT '投资人金额（分）';
ALTER TABLE `split_snapshot` MODIFY COLUMN `supplier_amount` bigint NOT NULL DEFAULT 0 COMMENT '供应商金额（分）';
ALTER TABLE `split_snapshot` MODIFY COLUMN `platform_commission` bigint NOT NULL DEFAULT 0 COMMENT '平台佣金（分）';
ALTER TABLE `split_snapshot` MODIFY COLUMN `platform_bonus` bigint NOT NULL DEFAULT 0 COMMENT '平台奖励（分）';
ALTER TABLE `split_snapshot` MODIFY COLUMN `total_check` varchar(16) NULL COMMENT '总额校验';
ALTER TABLE `split_snapshot` MODIFY COLUMN `status` varchar(16) NULL COMMENT '状态';
ALTER TABLE `split_snapshot` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `split_snapshot` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `split_snapshot` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `store_profile` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `store_profile` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `store_profile` MODIFY COLUMN `city` varchar(64) NULL COMMENT '城市';
ALTER TABLE `store_profile` MODIFY COLUMN `address` varchar(255) NULL COMMENT '地址';
ALTER TABLE `store_profile` MODIFY COLUMN `phone` varchar(32) NULL COMMENT '联系电话';
ALTER TABLE `store_profile` MODIFY COLUMN `latitude` decimal(10,6) NULL COMMENT '纬度';
ALTER TABLE `store_profile` MODIFY COLUMN `longitude` decimal(10,6) NULL COMMENT '经度';
ALTER TABLE `store_profile` MODIFY COLUMN `store_type` varchar(64) NULL COMMENT '门店类型';
ALTER TABLE `store_profile` MODIFY COLUMN `manager` varchar(64) NULL COMMENT '店长';
ALTER TABLE `store_profile` MODIFY COLUMN `investor_subject_id` bigint unsigned NULL COMMENT '投资人主体ID';
ALTER TABLE `store_profile` MODIFY COLUMN `business_hours` varchar(64) NULL COMMENT '营业时间';
ALTER TABLE `store_profile` MODIFY COLUMN `modes` json NULL COMMENT '经营模式(JSON)';
ALTER TABLE `store_profile` MODIFY COLUMN `promotion` varchar(255) NULL COMMENT '促销信息';
ALTER TABLE `store_profile` MODIFY COLUMN `queue_count` int NOT NULL DEFAULT 0 COMMENT '排队数';
ALTER TABLE `store_profile` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `store_profile` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `store_profile` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `stored_value_order` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `stored_value_order` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '充值单号';
ALTER TABLE `stored_value_order` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `stored_value_order` MODIFY COLUMN `package_id` bigint unsigned NOT NULL COMMENT '套餐ID';
ALTER TABLE `stored_value_order` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '金额（分）';
ALTER TABLE `stored_value_order` MODIFY COLUMN `pay_status` varchar(16) NOT NULL DEFAULT 'UNPAID' COMMENT '支付状态 UNPAID/PAID';
ALTER TABLE `stored_value_order` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `stored_value_order` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `stored_value_order` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `stored_value_package` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `stored_value_package` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '套餐编码';
ALTER TABLE `stored_value_package` MODIFY COLUMN `name` varchar(128) NOT NULL COMMENT '套餐名称';
ALTER TABLE `stored_value_package` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '金额（分）';
ALTER TABLE `stored_value_package` MODIFY COLUMN `status` varchar(16) NOT NULL DEFAULT 'enabled' COMMENT '状态 enabled启用 disabled停用';
ALTER TABLE `stored_value_package` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `stored_value_package` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `stored_value_package` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `stored_value_package_coupon` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `stored_value_package_coupon` MODIFY COLUMN `package_id` bigint unsigned NOT NULL COMMENT '套餐ID';
ALTER TABLE `stored_value_package_coupon` MODIFY COLUMN `coupon_id` bigint unsigned NOT NULL COMMENT '优惠券ID';
ALTER TABLE `stored_value_package_coupon` MODIFY COLUMN `count` int NOT NULL DEFAULT 0 COMMENT '赠送数量';
ALTER TABLE `stored_value_package_coupon` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `stored_value_package_coupon` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `stored_value_package_coupon` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `stored_value_txn` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `stored_value_txn` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `stored_value_txn` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `subject_account` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `subject_account` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `subject_account` MODIFY COLUMN `role_type` varchar(32) NOT NULL COMMENT '角色类型';
ALTER TABLE `subject_account` MODIFY COLUMN `available_balance` bigint NOT NULL DEFAULT 0 COMMENT '可用余额（分）';
ALTER TABLE `subject_account` MODIFY COLUMN `frozen_balance` bigint NOT NULL DEFAULT 0 COMMENT '冻结余额（分）';
ALTER TABLE `subject_account` MODIFY COLUMN `total_income` bigint NOT NULL DEFAULT 0 COMMENT '累计收入（分）';
ALTER TABLE `subject_account` MODIFY COLUMN `total_withdrawn` bigint NOT NULL DEFAULT 0 COMMENT '累计提现（分）';
ALTER TABLE `subject_account` MODIFY COLUMN `version` int NOT NULL DEFAULT 0 COMMENT '乐观锁版本号';
ALTER TABLE `subject_account` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `subject_account` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `subject_account` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `supplier_profile` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `supplier_profile` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `supplier_profile` MODIFY COLUMN `status` varchar(32) NULL COMMENT '状态';
ALTER TABLE `supplier_profile` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `supplier_profile` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `supplier_profile` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `dict_type` varchar(64) NOT NULL COMMENT '字典类型编码';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `item_code` varchar(64) NOT NULL COMMENT '字典项编码';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `item_name` varchar(64) NOT NULL COMMENT '字典项名称';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `enabled` tinyint NOT NULL DEFAULT 1 COMMENT '1启用 0停用';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `sys_dict_item` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `dict_type` varchar(64) NOT NULL COMMENT '字典类型编码';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `dict_name` varchar(64) NOT NULL COMMENT '字典类型名称';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `sys_dict_type` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `sys_menu` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_menu` MODIFY COLUMN `parent_id` bigint unsigned NOT NULL DEFAULT 0 COMMENT '父菜单ID';
ALTER TABLE `sys_menu` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '菜单名称';
ALTER TABLE `sys_menu` MODIFY COLUMN `path` varchar(128) NULL COMMENT '路由路径';
ALTER TABLE `sys_menu` MODIFY COLUMN `component` varchar(128) NULL COMMENT '组件路径';
ALTER TABLE `sys_menu` MODIFY COLUMN `perms` varchar(128) NULL COMMENT '权限标识';
ALTER TABLE `sys_menu` MODIFY COLUMN `type` varchar(16) NOT NULL DEFAULT 'menu' COMMENT '类型 menu菜单/button按钮等';
ALTER TABLE `sys_menu` MODIFY COLUMN `icon` varchar(64) NULL COMMENT '图标';
ALTER TABLE `sys_menu` MODIFY COLUMN `order_num` int NOT NULL DEFAULT 0 COMMENT '排序值，越小越靠前';
ALTER TABLE `sys_menu` MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用';
ALTER TABLE `sys_menu` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `sys_menu` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `sys_menu` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `sys_role` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_role` MODIFY COLUMN `code` varchar(64) NOT NULL COMMENT '角色编码';
ALTER TABLE `sys_role` MODIFY COLUMN `name` varchar(64) NOT NULL COMMENT '角色名称';
ALTER TABLE `sys_role` MODIFY COLUMN `data_scope` varchar(32) NULL COMMENT '数据权限范围';
ALTER TABLE `sys_role` MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '状态 1启用 0停用';
ALTER TABLE `sys_role` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `sys_role` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `sys_role` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `sys_role_menu` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_role_menu` MODIFY COLUMN `role_id` bigint unsigned NOT NULL COMMENT '角色ID';
ALTER TABLE `sys_role_menu` MODIFY COLUMN `menu_id` bigint unsigned NOT NULL COMMENT '菜单ID';
ALTER TABLE `sys_role_menu` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `sys_role_menu` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `sys_role_menu` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `sys_user` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_user` MODIFY COLUMN `username` varchar(64) NOT NULL COMMENT '用户名';
ALTER TABLE `sys_user` MODIFY COLUMN `password` varchar(100) NOT NULL COMMENT '密码（加密）';
ALTER TABLE `sys_user` MODIFY COLUMN `nick_name` varchar(64) NULL COMMENT '昵称';
ALTER TABLE `sys_user` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `sys_user` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `sys_user` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `sys_user_role` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `sys_user_role` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `sys_user_role` MODIFY COLUMN `role_id` bigint unsigned NOT NULL COMMENT '角色ID';
ALTER TABLE `sys_user_role` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `sys_user_role` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `sys_user_role` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `user_coupon` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `user_coupon` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `user_coupon` MODIFY COLUMN `coupon_id` bigint unsigned NOT NULL COMMENT '优惠券ID';
ALTER TABLE `user_coupon` MODIFY COLUMN `receive_time` datetime NULL COMMENT '领取时间';
ALTER TABLE `user_coupon` MODIFY COLUMN `lock_order_id` bigint unsigned NULL COMMENT '锁定订单ID';
ALTER TABLE `user_coupon` MODIFY COLUMN `use_time` datetime NULL COMMENT '使用时间';
ALTER TABLE `user_coupon` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `user_coupon` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `user_coupon` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `user_role_grant` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `user_role_grant` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `user_role_grant` MODIFY COLUMN `role_code` varchar(64) NOT NULL COMMENT '角色编码';
ALTER TABLE `user_role_grant` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `user_role_grant` MODIFY COLUMN `data_scope` varchar(32) NULL COMMENT '数据权限范围';
ALTER TABLE `user_role_grant` MODIFY COLUMN `grant_by` varchar(64) NULL COMMENT '授权人';
ALTER TABLE `user_role_grant` MODIFY COLUMN `grant_time` datetime NULL COMMENT '授权时间';
ALTER TABLE `user_role_grant` MODIFY COLUMN `status` varchar(32) NULL COMMENT '状态';
ALTER TABLE `user_role_grant` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `user_role_grant` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `user_role_grant` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `verify_record` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `verify_record` MODIFY COLUMN `verify_code` varchar(64) NOT NULL COMMENT '核销码';
ALTER TABLE `verify_record` MODIFY COLUMN `order_id` bigint unsigned NULL COMMENT '订单ID';
ALTER TABLE `verify_record` MODIFY COLUMN `order_no` varchar(64) NOT NULL COMMENT '订单号';
ALTER TABLE `verify_record` MODIFY COLUMN `store_subject_id` bigint unsigned NULL COMMENT '门店主体ID';
ALTER TABLE `verify_record` MODIFY COLUMN `operator` varchar(64) NULL COMMENT '操作人';
ALTER TABLE `verify_record` MODIFY COLUMN `device` varchar(64) NULL COMMENT '设备';
ALTER TABLE `verify_record` MODIFY COLUMN `result` varchar(16) NULL COMMENT '核销结果';
ALTER TABLE `verify_record` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `verify_record` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `verify_record` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
ALTER TABLE `withdrawal` MODIFY COLUMN `id` bigint unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID';
ALTER TABLE `withdrawal` MODIFY COLUMN `withdraw_no` varchar(64) NOT NULL COMMENT '提现单号';
ALTER TABLE `withdrawal` MODIFY COLUMN `user_id` bigint unsigned NOT NULL COMMENT '用户ID';
ALTER TABLE `withdrawal` MODIFY COLUMN `subject_id` bigint unsigned NOT NULL COMMENT '主体ID';
ALTER TABLE `withdrawal` MODIFY COLUMN `role_type` varchar(32) NOT NULL COMMENT '角色类型';
ALTER TABLE `withdrawal` MODIFY COLUMN `amount` bigint NOT NULL DEFAULT 0 COMMENT '提现金额（分）';
ALTER TABLE `withdrawal` MODIFY COLUMN `fee` bigint NOT NULL DEFAULT 0 COMMENT '手续费（分）';
ALTER TABLE `withdrawal` MODIFY COLUMN `apply_time` datetime NULL COMMENT '申请时间';
ALTER TABLE `withdrawal` MODIFY COLUMN `review_time` datetime NULL COMMENT '审核时间';
ALTER TABLE `withdrawal` MODIFY COLUMN `pay_time` datetime NULL COMMENT '打款时间';
ALTER TABLE `withdrawal` MODIFY COLUMN `callback_time` datetime NULL COMMENT '回调时间';
ALTER TABLE `withdrawal` MODIFY COLUMN `failure_reason` varchar(255) NULL COMMENT '失败原因';
ALTER TABLE `withdrawal` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `withdrawal` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `withdrawal` MODIFY COLUMN `deleted` tinyint NOT NULL DEFAULT 0 COMMENT '逻辑删除 0未删 1已删';
