-- =============================================================
-- 回滚脚本：清空 V62 手动新增的字段注释
-- 原理：把 COMMENT 改为空字符串 ''，字段类型/默认值/可空不变
-- 执行：docker exec -i wuling-mysql mysql -uroot -p wuling < 本文件
-- =============================================================

ALTER TABLE `app_config`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `sort` INT          NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` VARCHAR(16)  NOT NULL DEFAULT 'enabled' COMMENT '',
  MODIFY COLUMN `remark` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT      NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `app_user`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `open_id` VARCHAR(64)  NOT NULL COMMENT '',
  MODIFY COLUMN `union_id` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `nick_name` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `avatar` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `phone` VARCHAR(20)  NULL COMMENT '',
  MODIFY COLUMN `birthday` DATE         NULL COMMENT '',
  MODIFY COLUMN `gender` VARCHAR(16)  NULL COMMENT '',
  MODIFY COLUMN `vip_level` VARCHAR(16)  NULL COMMENT '',
  MODIFY COLUMN `business_role` VARCHAR(32)  NULL COMMENT '',
  MODIFY COLUMN `bound_subject_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `referrer_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `channel_subject_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT      NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT      NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `audit_log`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `operator` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `module` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `action` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `target` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `before_value` TEXT NULL COMMENT '',
  MODIFY COLUMN `after_value` TEXT NULL COMMENT '',
  MODIFY COLUMN `reason` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `ip` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `balance_pay_intent`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `biz_role`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `description` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `biz_subject`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64)  NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32)  NULL COMMENT '',
  MODIFY COLUMN `bound_user_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT      NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `channel_profile`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `location` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `store_type` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `channel_store`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `channel_subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `store_subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `comments`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `order_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `rating` INT NOT NULL DEFAULT 5 COMMENT '',
  MODIFY COLUMN `content` TEXT NULL COMMENT '',
  MODIFY COLUMN `images` JSON NULL COMMENT '',
  MODIFY COLUMN `review_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `coupon`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `type` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `threshold` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `brand` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `scenes` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `source` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `description` TEXT NULL COMMENT '',
  MODIFY COLUMN `image` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `validity_type` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `validity_start` DATETIME NULL COMMENT '',
  MODIFY COLUMN `validity_end` DATETIME NULL COMMENT '',
  MODIFY COLUMN `validity_days` INT NULL COMMENT '',
  MODIFY COLUMN `usage_time` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `applicable_store_ids` JSON NULL COMMENT '',
  MODIFY COLUMN `applicable_product_ids` JSON NULL COMMENT '',
  MODIFY COLUMN `stock` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'enabled' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `event_outbox`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE `exchange_order`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `exchange_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `points_product_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `points` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `pickup_code` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `feature_flag`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `default_status` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `current_status` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `open_condition` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `fund_flow`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `flow_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `role_type` VARCHAR(32) NOT NULL COMMENT '',
  MODIFY COLUMN `direction` VARCHAR(8) NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `balance_after` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `remark` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `fund_pool`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `pool_name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `total_balance` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `gift_card`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `card_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `denomination_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'INACTIVE' COMMENT '',
  MODIFY COLUMN `owner_user_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `gift_card_denomination`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'enabled' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `gift_card_group`
  MODIFY COLUMN `code` VARCHAR(64)  NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `sort` INT          NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `deleted` TINYINT      NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE `gift_card_order`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `denomination_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `pay_status` VARCHAR(16) NOT NULL DEFAULT 'UNPAID' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `gift_card_refund`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `refund_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `growth_record`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `investor_profile`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `investable_store_count` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `sign_status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `member_level`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `level_code` VARCHAR(16) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `discount` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `benefits` JSON        NULL COMMENT '',
  MODIFY COLUMN `sort` INT         NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT     NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `order_item`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `order_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `product_id` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `product_name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `spec_snapshot` JSON NULL COMMENT '',
  MODIFY COLUMN `unit_price` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `original_price` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `quantity` INT NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `sub_total` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `orders`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `store_subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `channel_subject_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `meal_type` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `pickup_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'CREATED' COMMENT '',
  MODIFY COLUMN `pay_status` VARCHAR(16) NOT NULL DEFAULT 'UNPAID' COMMENT '',
  MODIFY COLUMN `pickup_code` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `total_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `original_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `discount_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `paid_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `coupon_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `coupon_discount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `points_used` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `points_earned` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `refund_status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `remark` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `pay_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `verify_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `complete_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `payment`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `payment_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `order_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `channel` VARCHAR(16) NOT NULL COMMENT '',
  MODIFY COLUMN `third_status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `standard_status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `transaction_id` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `callback_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `platform_profile`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `app_id` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `app_secret` VARCHAR(128) NULL COMMENT '',
  MODIFY COLUMN `pay_config` JSON NULL COMMENT '',
  MODIFY COLUMN `split_default` JSON NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `points_category`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `points_earning_rule`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `action` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `reward` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `note` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `sort` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `points_product`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `image` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `points` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `stock` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `badge` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `limit_text` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `description` TEXT NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'enabled' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `points_record`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `balance_after` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `source` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `remark` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `points_signin`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `sign_date` DATE NOT NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `points_signin_rule`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `daily` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `streak_days` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `streak_reward` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `product`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `product_id` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `category_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `tags` JSON NULL COMMENT '',
  MODIFY COLUMN `description` TEXT NULL COMMENT '',
  MODIFY COLUMN `price` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `original_price` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `stored_value_price` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `image` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `ingredients` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `allergens` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `cup_capacity` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `tips` JSON NULL COMMENT '',
  MODIFY COLUMN `on_sale` TINYINT NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `split_rule_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `product_category`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `sort` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `product_spec`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `product_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `group_code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `group_label` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `option_code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `option_label` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `price_delta` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `selected` TINYINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `icon` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `sort` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `product_store`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `product_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `store_subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `reconcile_issue`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `issue_type` VARCHAR(32) NOT NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `system_value` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `third_value` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `diff_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `found_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `referral_config`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `config` JSON NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `referral_record`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `inviter_user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `invitee_user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `first_order_status` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `refund`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `refund_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `order_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `reason` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `apply_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `review_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `complete_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `region`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `code` VARCHAR(32) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `sort` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `role_application`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `role_type` VARCHAR(32) NOT NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '',
  MODIFY COLUMN `apply_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `review_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `reviewer` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `settlement_record`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `record_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `snapshot_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `order_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `settle_date` DATE NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `spec_group_template`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `sort` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `spec_option_template`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `group_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `price_delta` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `icon` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `sort` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `split_rule`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `product_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `platform_ratio` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `store_ratio` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `channel_ratio` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `investor_ratio` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `supplier_ratio` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'enabled' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `split_snapshot`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `snapshot_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `order_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `item_count` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `platform_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `store_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `channel_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `investor_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `supplier_amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `platform_commission` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `platform_bonus` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `total_check` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `store_profile`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `city` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `address` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `phone` VARCHAR(32)  NULL COMMENT '',
  MODIFY COLUMN `latitude` DECIMAL(10,6) NULL COMMENT '',
  MODIFY COLUMN `longitude` DECIMAL(10,6) NULL COMMENT '',
  MODIFY COLUMN `store_type` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `manager` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `investor_subject_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `business_hours` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `modes` JSON         NULL COMMENT '',
  MODIFY COLUMN `promotion` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `queue_count` INT          NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT      NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `stored_value_order`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `package_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `pay_status` VARCHAR(16) NOT NULL DEFAULT 'UNPAID' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `stored_value_package`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(128) NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` VARCHAR(16) NOT NULL DEFAULT 'enabled' COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `stored_value_package_coupon`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `package_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `coupon_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `count` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `stored_value_txn`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '';

ALTER TABLE `subject_account`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `role_type` VARCHAR(32) NOT NULL COMMENT '',
  MODIFY COLUMN `available_balance` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `frozen_balance` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `total_income` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `total_withdrawn` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `version` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `supplier_profile`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `product_count` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `sys_dict_item`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `dict_type_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `dict_type` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `item_code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `item_name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `sort` INT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `enabled` TINYINT NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `extra` JSON NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `sys_dict_type`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `dict_type` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `dict_name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `sys_menu`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `parent_id` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64)  NOT NULL COMMENT '',
  MODIFY COLUMN `path` VARCHAR(128) NULL COMMENT '',
  MODIFY COLUMN `component` VARCHAR(128) NULL COMMENT '',
  MODIFY COLUMN `perms` VARCHAR(128) NULL COMMENT '',
  MODIFY COLUMN `type` VARCHAR(16)  NOT NULL DEFAULT 'menu' COMMENT '',
  MODIFY COLUMN `icon` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `order_num` INT          NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `status` TINYINT      NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT      NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `sys_role`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `name` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `data_scope` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `status` TINYINT     NOT NULL DEFAULT 1 COMMENT '',
  MODIFY COLUMN `create_time` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME    NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT     NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `sys_role_menu`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `menu_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `sys_user`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `username` VARCHAR(64)  NOT NULL COMMENT '',
  MODIFY COLUMN `password` VARCHAR(100) NOT NULL COMMENT '',
  MODIFY COLUMN `nick_name` VARCHAR(64)  NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT      NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `sys_user_role`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `role_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `user_coupon`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `coupon_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `receive_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `lock_order_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `use_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `user_role_grant`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `role_code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `data_scope` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `grant_by` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `grant_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `status` VARCHAR(32) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `verify_record`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `verify_code` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `order_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `order_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `store_subject_id` BIGINT UNSIGNED NULL COMMENT '',
  MODIFY COLUMN `operator` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `device` VARCHAR(64) NULL COMMENT '',
  MODIFY COLUMN `result` VARCHAR(16) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';

ALTER TABLE `withdrawal`
  MODIFY COLUMN `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '',
  MODIFY COLUMN `withdraw_no` VARCHAR(64) NOT NULL COMMENT '',
  MODIFY COLUMN `user_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `subject_id` BIGINT UNSIGNED NOT NULL COMMENT '',
  MODIFY COLUMN `role_type` VARCHAR(32) NOT NULL COMMENT '',
  MODIFY COLUMN `amount` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `fee` BIGINT NOT NULL DEFAULT 0 COMMENT '',
  MODIFY COLUMN `apply_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `review_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `pay_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `callback_time` DATETIME NULL COMMENT '',
  MODIFY COLUMN `failure_reason` VARCHAR(255) NULL COMMENT '',
  MODIFY COLUMN `create_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `update_time` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '',
  MODIFY COLUMN `deleted` TINYINT  NOT NULL DEFAULT 0 COMMENT '';
