/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  auth_grant: () => import("@/views/auth/grant/index.vue"),
  auth_role: () => import("@/views/auth/role/index.vue"),
  auth_wechat: () => import("@/views/auth/wechat/index.vue"),
  finance_account: () => import("@/views/finance/account/index.vue"),
  finance_flow: () => import("@/views/finance/flow/index.vue"),
  finance_pool: () => import("@/views/finance/pool/index.vue"),
  finance_reconcile: () => import("@/views/finance/reconcile/index.vue"),
  "finance_snapshot-detail": () => import("@/views/finance/snapshot-detail/index.vue"),
  finance_snapshot: () => import("@/views/finance/snapshot/index.vue"),
  finance_withdraw: () => import("@/views/finance/withdraw/index.vue"),
  home: () => import("@/views/home/index.vue"),
  marketing_comment: () => import("@/views/marketing/comment/index.vue"),
  marketing_coupon: () => import("@/views/marketing/coupon/index.vue"),
  marketing_exchange: () => import("@/views/marketing/exchange/index.vue"),
  "marketing_gift-order": () => import("@/views/marketing/gift-order/index.vue"),
  marketing_gift: () => import("@/views/marketing/gift/index.vue"),
  marketing_member: () => import("@/views/marketing/member/index.vue"),
  "marketing_points-rule": () => import("@/views/marketing/points-rule/index.vue"),
  marketing_points: () => import("@/views/marketing/points/index.vue"),
  marketing_referral: () => import("@/views/marketing/referral/index.vue"),
  marketing_stored: () => import("@/views/marketing/stored/index.vue"),
  product_category: () => import("@/views/product/category/index.vue"),
  product_list: () => import("@/views/product/list/index.vue"),
  product_split: () => import("@/views/product/split/index.vue"),
  "review_role-detail": () => import("@/views/review/role-detail/index.vue"),
  review_role: () => import("@/views/review/role/index.vue"),
  subject_channel: () => import("@/views/subject/channel/index.vue"),
  subject_investor: () => import("@/views/subject/investor/index.vue"),
  subject_platform: () => import("@/views/subject/platform/index.vue"),
  subject_store: () => import("@/views/subject/store/index.vue"),
  subject_supplier: () => import("@/views/subject/supplier/index.vue"),
  system_audit: () => import("@/views/system/audit/index.vue"),
  system_city: () => import("@/views/system/city/index.vue"),
  system_config: () => import("@/views/system/config/index.vue"),
  system_dict: () => import("@/views/system/dict/index.vue"),
  system_feature: () => import("@/views/system/feature/index.vue"),
  "trade_order-detail": () => import("@/views/trade/order-detail/index.vue"),
  trade_order: () => import("@/views/trade/order/index.vue"),
  trade_payment: () => import("@/views/trade/payment/index.vue"),
  trade_refund: () => import("@/views/trade/refund/index.vue"),
  "trade_verify-detail": () => import("@/views/trade/verify-detail/index.vue"),
  "trade_verify-pool": () => import("@/views/trade/verify-pool/index.vue"),
  trade_verify: () => import("@/views/trade/verify/index.vue"),
  user_list: () => import("@/views/user/list/index.vue"),
};
