/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'auth',
    path: '/auth',
    component: 'layout.base',
    meta: {
      title: '授权中心',
      icon: 'mdi:shield-account',
      order: 20,
      roles: ['R_SUPER'],
      i18nKey: null
    },
    children: [
      {
        name: 'auth_account',
        path: '/auth/account',
        component: 'view.auth_account',
        meta: {
          title: '账号管理',
          order: 2,
          roles: ['R_SUPER'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'auth_grant',
        path: '/auth/grant',
        component: 'view.auth_grant',
        meta: {
          title: '角色授权记录',
          order: 3,
          roles: ['R_SUPER'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'auth_role',
        path: '/auth/role',
        component: 'view.auth_role',
        meta: {
          title: '角色与权限',
          order: 1,
          roles: ['R_SUPER'],
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'finance',
    path: '/finance',
    component: 'layout.base',
    meta: {
      title: '财务中心',
      icon: 'mdi:wallet',
      order: 50,
      roles: ['R_SUPER', 'R_FINANCE'],
      i18nKey: null
    },
    children: [
      {
        name: 'finance_account',
        path: '/finance/account',
        component: 'view.finance_account',
        meta: {
          title: '经营方账户',
          order: 2,
          roles: ['R_SUPER', 'R_FINANCE'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'finance_flow',
        path: '/finance/flow',
        component: 'view.finance_flow',
        meta: {
          title: '资金流水',
          order: 3,
          roles: ['R_SUPER', 'R_FINANCE'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'finance_pool',
        path: '/finance/pool',
        component: 'view.finance_pool',
        meta: {
          title: '资金池',
          order: 1,
          roles: ['R_SUPER', 'R_FINANCE'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'finance_reconcile',
        path: '/finance/reconcile',
        component: 'view.finance_reconcile',
        meta: {
          title: '对账异常池',
          order: 5,
          roles: ['R_SUPER', 'R_FINANCE'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'finance_snapshot',
        path: '/finance/snapshot',
        component: 'view.finance_snapshot',
        meta: {
          title: '分账快照',
          order: 4,
          roles: ['R_SUPER', 'R_FINANCE'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'finance_snapshot-detail',
        path: '/finance/snapshot-detail',
        component: 'view.finance_snapshot-detail',
        meta: {
          title: '分账快照详情',
          roles: ['R_SUPER', 'R_FINANCE'],
          hideInMenu: true,
          i18nKey: null
        }
      },
      {
        name: 'finance_withdraw',
        path: '/finance/withdraw',
        component: 'view.finance_withdraw',
        meta: {
          title: '提现管理',
          order: 6,
          roles: ['R_SUPER', 'R_FINANCE'],
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home'
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'marketing',
    path: '/marketing',
    component: 'layout.base',
    meta: {
      title: '营销中心',
      icon: 'mdi:bullhorn',
      order: 45,
      roles: ['R_SUPER', 'R_OPERATION'],
      i18nKey: null
    },
    children: [
      {
        name: 'marketing_coupon',
        path: '/marketing/coupon',
        component: 'view.marketing_coupon',
        meta: {
          title: '优惠券管理',
          order: 1,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_COUPON',
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_exchange',
        path: '/marketing/exchange',
        component: 'view.marketing_exchange',
        meta: {
          title: '兑换记录',
          order: 9,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_STORED_VALUE',
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_gift',
        path: '/marketing/gift',
        component: 'view.marketing_gift',
        meta: {
          title: '礼品卡',
          order: 3,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_STORED_VALUE',
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_gift-order',
        path: '/marketing/gift-order',
        component: 'view.marketing_gift-order',
        meta: {
          title: '礼品卡订单',
          order: 8,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_STORED_VALUE',
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_member',
        path: '/marketing/member',
        component: 'view.marketing_member',
        meta: {
          title: '会员等级',
          order: 6,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_STORED_VALUE',
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_points',
        path: '/marketing/points',
        component: 'view.marketing_points',
        meta: {
          title: '积分商城',
          order: 5,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_STORED_VALUE',
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_points-category',
        path: '/marketing/points-category',
        component: 'view.marketing_points-category',
        meta: {
          title: '积分商城分类',
          hideInMenu: true,
          activeMenu: 'marketing_points',
          order: 4,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_STORED_VALUE',
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_points-rule',
        path: '/marketing/points-rule',
        component: 'view.marketing_points-rule',
        meta: {
          title: '签到规则',
          i18nKey: 'route.marketing_points-rule'
        }
      },
      {
        name: 'marketing_referral',
        path: '/marketing/referral',
        component: 'view.marketing_referral',
        meta: {
          title: '分享有礼',
          order: 10,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'marketing_stored',
        path: '/marketing/stored',
        component: 'view.marketing_stored',
        meta: {
          title: '储值套餐',
          order: 2,
          roles: ['R_SUPER', 'R_OPERATION'],
          featureFlag: 'ENABLE_STORED_VALUE',
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'product',
    path: '/product',
    component: 'layout.base',
    meta: {
      title: '商品中心',
      icon: 'mdi:cup-outline',
      order: 30,
      roles: ['R_SUPER', 'R_OPERATION'],
      i18nKey: null
    },
    children: [
      {
        name: 'product_category',
        path: '/product/category',
        component: 'view.product_category',
        meta: {
          title: '分类管理',
          order: 1,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'product_list',
        path: '/product/list',
        component: 'view.product_list',
        meta: {
          title: '商品管理',
          order: 2,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'product_split',
        path: '/product/split',
        component: 'view.product_split',
        meta: {
          title: '分账规则',
          order: 4,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'review',
    path: '/review',
    component: 'layout.base',
    meta: {
      title: '申请审核',
      icon: 'mdi:clipboard-text-clock',
      order: 25,
      roles: ['R_SUPER', 'R_OPERATION'],
      i18nKey: null
    },
    children: [
      {
        name: 'review_role',
        path: '/review/role',
        component: 'view.review_role',
        meta: {
          title: '角色开通审核',
          order: 1,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'review_role-detail',
        path: '/review/role-detail',
        component: 'view.review_role-detail',
        meta: {
          title: '角色开通审核详情',
          roles: ['R_SUPER', 'R_OPERATION'],
          hideInMenu: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'subject',
    path: '/subject',
    component: 'layout.base',
    meta: {
      title: '主体管理',
      icon: 'mdi:domain',
      order: 10,
      roles: ['R_SUPER', 'R_OPERATION'],
      i18nKey: null
    },
    children: [
      {
        name: 'subject_channel',
        path: '/subject/channel',
        component: 'view.subject_channel',
        meta: {
          title: '资源方管理',
          order: 3,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'subject_investor',
        path: '/subject/investor',
        component: 'view.subject_investor',
        meta: {
          title: '投资人管理',
          order: 4,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'subject_platform',
        path: '/subject/platform',
        component: 'view.subject_platform',
        meta: {
          title: '平台主体',
          order: 1,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'subject_store',
        path: '/subject/store',
        component: 'view.subject_store',
        meta: {
          title: '门店管理',
          order: 2,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'subject_supplier',
        path: '/subject/supplier',
        component: 'view.subject_supplier',
        meta: {
          title: '供应商管理',
          order: 5,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'system',
    path: '/system',
    component: 'layout.base',
    meta: {
      title: '系统审计',
      icon: 'mdi:shield',
      order: 60,
      roles: ['R_SUPER', 'R_AUDIT'],
      i18nKey: null
    },
    children: [
      {
        name: 'system_audit',
        path: '/system/audit',
        component: 'view.system_audit',
        meta: {
          title: '审计日志',
          order: 1,
          roles: ['R_SUPER', 'R_AUDIT'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'system_city',
        path: '/system/city',
        component: 'view.system_city',
        meta: {
          title: '城市管理',
          order: 4,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'system_config',
        path: '/system/config',
        component: 'view.system_config',
        meta: {
          title: 'system_config',
          i18nKey: 'route.system_config'
        }
      },
      {
        name: 'system_dict',
        path: '/system/dict',
        component: 'view.system_dict',
        meta: {
          title: '数据字典',
          order: 3,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'system_feature',
        path: '/system/feature',
        component: 'view.system_feature',
        meta: {
          title: '功能开关',
          order: 2,
          roles: ['R_SUPER', 'R_AUDIT'],
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'trade',
    path: '/trade',
    component: 'layout.base',
    meta: {
      title: '交易中心',
      icon: 'mdi:receipt-text',
      order: 40,
      roles: ['R_SUPER', 'R_OPERATION'],
      i18nKey: null
    },
    children: [
      {
        name: 'trade_order',
        path: '/trade/order',
        component: 'view.trade_order',
        meta: {
          title: '订单管理',
          order: 1,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'trade_order-detail',
        path: '/trade/order-detail',
        component: 'view.trade_order-detail',
        meta: {
          title: '订单详情',
          roles: ['R_SUPER', 'R_OPERATION'],
          hideInMenu: true,
          i18nKey: null
        }
      },
      {
        name: 'trade_payment',
        path: '/trade/payment',
        component: 'view.trade_payment',
        meta: {
          title: '支付记录',
          order: 2,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'trade_refund',
        path: '/trade/refund',
        component: 'view.trade_refund',
        meta: {
          title: '退款管理',
          order: 3,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'trade_verify',
        path: '/trade/verify',
        component: 'view.trade_verify',
        meta: {
          title: '核销记录',
          order: 5,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      },
      {
        name: 'trade_verify-detail',
        path: '/trade/verify-detail',
        component: 'view.trade_verify-detail',
        meta: {
          title: '核销记录详情',
          roles: ['R_SUPER', 'R_OPERATION'],
          hideInMenu: true,
          i18nKey: null
        }
      },
      {
        name: 'trade_verify-pool',
        path: '/trade/verify-pool',
        component: 'view.trade_verify-pool',
        meta: {
          title: '待核销池',
          order: 4,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  },
  {
    name: 'user',
    path: '/user',
    component: 'layout.base',
    meta: {
      title: '用户管理',
      icon: 'mdi:account-group',
      order: 15,
      roles: ['R_SUPER', 'R_OPERATION'],
      i18nKey: null
    },
    children: [
      {
        name: 'user_list',
        path: '/user/list',
        component: 'view.user_list',
        meta: {
          title: '用户列表',
          order: 1,
          roles: ['R_SUPER', 'R_OPERATION'],
          keepAlive: true,
          i18nKey: null
        }
      }
    ]
  }
];
